### ISSUE TITLE
nodesig and nodesigl - different results in R and shell

### ISSUE THREAD

**Issue by Dirtza** [ropensci/phylocomr#17]
Hi!
I am using the commands nodesig and nodesigl to calculate some "hotnodes". 
I have some test files to learn how to do it and discovered that I get different results if I run these commands in R or in the shell.

1. The rank and median are not exactly the same 
2. the node signals are different!!!

When I run it in R, the nexus file for nodsig has e.g. 6 nodes marked with "[%note = 'string:SIGMORE']". The command nodesigl gives me the table where significant nodes are marked with "+". However, in the table, there are 7 "+" - so one signal too much!

When I run it in the shell, exactly the opposite is happening:  7 nodes are marked with [%note = 'string:SIGMORE']" in the nexus file and only 6 nodes are labelled with "+". 

I use R studio Version 1.0.136, (R version 3.3.2) - however I can not use phylocomr under this version. (OS X, Version 10.9.5)
Thus I run phylocom via R like this: system("./phylocom nodesigl phylo sample > HotNode_test.txt") - could this maybe cause a problem?

Attached you will find the test files.
Thank you in advance!!

[Tree50_test.txt](https://github.com/ropensci/phylocomr/files/1018612/Tree50_test.txt)
[sample50_test.txt](https://github.com/ropensci/phylocomr/files/1018617/sample50_test.txt)

**Comment by sckott** [comment]
thanks for the issue @Dirtza  I will take a look at your question. 

> however I can not use phylocomr under this version. 

what do you mean?  You can not install `phylocomr`?  Not promising this will solve your problems, but good idea to upgrade to OSX Sierra and R 3.4.0  

What version of `phylocomr` are you using?

**Comment by Dirtza** [comment]
Hi!

Yes, my R version 3.3.2 might be a problem, I get the warning message 'package 'phylocomr' is not available (for R version 3.3.2)’ , so I will update it.

However, I think I found the answer to my problem and I’m sorry I bothered you:
It is normal do get different results of SIGMORE (nodesig) or the + (nodesigl) as the results depend on the unique randomisation that is done for each run. So actually I get slightly different results all the time - and it shouldn’t matter if I run it in the shell or R! I didn’t pay attention to that fact and only after I send my message, I realised that is might have to do something with the unique randomisation that is done for each calculation.

I’m sorry I ‘sat the cat amongst the pigeon’ for no reason.

Thank you very much for your quick reply, I really appreciate this!



On 22 May 2017, at 20:56, Scott Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


thanks for the issue @Dirtza<https://github.com/dirtza> I will take a look at your question.

however I can not use phylocomr under this version.

what do you mean? You can not install phylocomr? Not promising this will solve your problems, but good idea to upgrade to OSX Sierra and R 3.4.0

What version of phylocomr are you using?

**Comment by sckott** [comment]
glad you figured it out!
